# train_config.yaml

models:
  base_model: "Qwen/Qwen2.5-3B"
  device: "mps"

training:
  load_adapter_path: null
  save_adapter_path: null
  verbose: true

# Global generation params that apply to all stages unless overridden
generation:
  max_new_tokens: 256
  stop_sequences:
    - "User:"
    - "System:"
    - "<|endoftext|>"

stages:
  - name: "stage1"
    method: "grpo"
    lr: 1e-6
    epochs: 5
    batch_size: 2
    G: 4

    dataset:
      path: "dataset/zero/verifier_samples_very_easy.jsonl"
      template: "src/cli/train/templates/prompt_template.jinja2"

    # Stage-specific generation settings
    generation:
      sampler: "top_p"
      temperature: 0.6
      top_p: 0.95

    # Block-sync + checkpoint options
    sync_every_n_batches: 50         # Refresh reference model after 50 mini-batches
    checkpoint_dir: "checkpoints/"   # Directory to save checkpoints
    checkpoint_every_n_batches: 100  # Save a checkpoint every 100 batches
    checkpoint_every_n_epochs: 1     # Also save a checkpoint at the end of each epoch
